---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512MiB
userSwapChoices:
    - none
    - reuse
    - file
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType: "ext4"
