---
showSupportUrl:         true
showKnownProblemsUrl:   true
showReleaseNotesUrl:    true

requirements:
    requiredRAM:   2.5
    requiredDiskSpace: 15.0
    internetCheckUrl:  http://example.com
    check:
        - storage
        - ram
        - power
    required:
        - ram
