---
modules-search: [ local ]

instances:
  - id:      sinix_postinstall
    module:  shellprocess
    config:  shellprocess.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - users
    - sinix_postinstall
    - umount
    - finish

branding: sinix
prompt-on-quit: true
defs-file: /etc/calamares/branding/sinix/branding.desc

